.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bsha3_qt test_bsha3_qt
clean: FORCE
	$(MAKE) -C .. bsha3_qt_clean test_bsha3_qt_clean
check: FORCE
	$(MAKE) -C .. test_bsha3_qt_check
bsha3-qt bsha3-qt.exe: FORCE
	 $(MAKE) -C .. bsha3_qt
